name: S1
version: '${project.version}'
main: stefano.s1.S1
api-version: 1.16
commands:
  sv:
    description: type(sendMessage)command list
  sv effects:
    description: type(playEffects)dragon breath
  sv tell origin:
    description: tyoe(sendMessage)tell origin
  sv tell cooperative:
    description: type(sendMessage)cooperative player
  sv tell homePageURL:
    description: type(sendMessage)SV homePage URL
  sv tp lobby:
    description: type(teleport)lobby
  sv tp athletic:
    description: type(teleport)athletic
  sv tp svinfo:
    description: type(teleport)sv information center
  sv tp pvpMap:
    description: type(teleport) restriction(!Playing_Game)pvpMap
  sv help:
    description: type(sendMessage) help
  sv title:
    description: type(title) title
  sv op c:
    description: type(op action) set gamemode creative
  sv op s:
    description: type(op action) set gamemode survival
  sv hello:
    description: type(sendMessage) world introduce
  sv notice:
    description: type(sendMessage) latest notice
